/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as RaffleRouteImport } from './routes/raffle'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as GameSlugRouteImport } from './routes/game.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleRoute = RaffleRouteImport.update({
  id: '/raffle',
  path: '/raffle',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSlugRoute = GameSlugRouteImport.update({
  id: '/game/$slug',
  path: '/game/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/quest': typeof QuestRoute
  '/raffle': typeof RaffleRoute
  '/wallet': typeof WalletRoute
  '/wheel': typeof WheelRoute
  '/game/$slug': typeof GameSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/quest': typeof QuestRoute
  '/raffle': typeof RaffleRoute
  '/wallet': typeof WalletRoute
  '/wheel': typeof WheelRoute
  '/game/$slug': typeof GameSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/quest': typeof QuestRoute
  '/raffle': typeof RaffleRoute
  '/wallet': typeof WalletRoute
  '/wheel': typeof WheelRoute
  '/game/$slug': typeof GameSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/quest'
    | '/raffle'
    | '/wallet'
    | '/wheel'
    | '/game/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/quest'
    | '/raffle'
    | '/wallet'
    | '/wheel'
    | '/game/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/quest'
    | '/raffle'
    | '/wallet'
    | '/wheel'
    | '/game/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  QuestRoute: typeof QuestRoute
  RaffleRoute: typeof RaffleRoute
  WalletRoute: typeof WalletRoute
  WheelRoute: typeof WheelRoute
  GameSlugRoute: typeof GameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle': {
      id: '/raffle'
      path: '/raffle'
      fullPath: '/raffle'
      preLoaderRoute: typeof RaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$slug': {
      id: '/game/$slug'
      path: '/game/$slug'
      fullPath: '/game/$slug'
      preLoaderRoute: typeof GameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  QuestRoute: QuestRoute,
  RaffleRoute: RaffleRoute,
  WalletRoute: WalletRoute,
  WheelRoute: WheelRoute,
  GameSlugRoute: GameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
